### PR TITLE
Websockets webapp now works on Cache 16.1+  Normal installs

### PR DESCRIPTION
**Pull request by eduard93**

### CODE REVIEW

**Comment by eduard93** [comment]
For https://github.com/intersystems-ru/webterminal/issues/54

**Comment by ZitRos** [comment]
Thanks Edward - you're lightning fast! I planned to see this issue today, and you've done it in minutes before I reached the thought to look through it.

Please, see the comments on commits [here](https://github.com/intersystems-ru/webterminal/commit/3c0471abfe480892555eae1163b23232cc0aa482) and [here](https://github.com/intersystems-ru/webterminal/commit/d8979cdca97dad5a2283a5f395d6adad4ae8e7a5) - once they'd be resolved I accept this pull request.

Thank you!

**Comment by eduard93** [comment]
Fixed comments in the last commit

**Comment by ZitRos** [comment]
Awesome, thank you!

**Pull request merged**
