### PR TITLE
Removed Const from parameters' names. They are now distinguishable by # syntax

### PR DESCRIPTION
**Pull request by eduard93**

### CODE REVIEW

**Comment by ZitRos** [comment]
OK!

**Comment by ZitRos** [comment]
@eduard93, I have missed that you accidentally rewrote version inject here, and fixed this with b8287dd26ad9667fec4afc55b56f74529ffb18c5. Please, pay attention to diffs.

**Comment by eduard93** [comment]
Sorry, my bad.

**Comment by ZitRos** [comment]
No worries! Great contributions, then.

**Pull request merged**
